import type { Campaign } from "@/types";

const img = (id: string, w = 1200) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=70`;

export const campaigns: Campaign[] = [
  {
    id: "c1",
    slug: "sponsor-a-software-engineering-student",
    title: "Sponsor a Software Engineering Student",
    tagline: "Fund one year of intensive IT training for a deserving student.",
    description:
      "Your donation covers tuition, course materials, and a laptop stipend for students from low-income families enrolled in SMIT's flagship software engineering track.",
    story: [
      "Every batch, thousands of bright young Pakistanis apply to SMIT's free IT training programs — but demand far exceeds the seats we can fund. Many applicants are the first in their family to pursue higher education, and a single sponsored seat can change a household's future income for good.",
      "A full sponsorship of Rs. 25,000 covers one student's year: instructor time, lab access, learning materials, and assessment costs. Graduates of this track routinely move into junior developer roles within months of completing the program.",
      "When you sponsor a student, you are not giving charity — you are making an investment that pays out in salaries, dignity, and a growing tech ecosystem for Pakistan.",
    ],
    imageUrl: "/media/children-labour.jpg",
    gallery: [
      "/media/children-labour.jpg",
      img("photo-1503676260728-1c00da094a0b"),
      img("photo-1461749280684-dccba630e2f6"),
    ],
    category: "Education",
    location: "Karachi",
    goalAmount: 2500000,
    raisedAmount: 1842500,
    donorCount: 412,
    currency: "PKR",
    status: "active",
    createdAt: "2026-03-14T09:00:00Z",
    endsAt: "2026-09-30T23:59:59Z",
  },
  {
    id: "c2",
    slug: "emergency-flood-relief-sindh",
    title: "Emergency Flood Relief — Interior Sindh",
    tagline: "Food packs, clean water, and shelter for flood-displaced families.",
    description:
      "Monsoon flooding has displaced thousands of families across interior Sindh. We are on the ground distributing ration packs, safe drinking water, tents, and medical aid.",
    story: [
      "This monsoon season has hit interior Sindh with devastating force. Entire villages are underwater, and families who already lived at the margin have lost homes, crops, and livestock overnight.",
      "Our volunteer teams are on the ground right now. Rs. 7,500 delivers a family ration pack that lasts a month. Rs. 15,000 adds a hygiene kit and safe drinking water. Rs. 35,000 shelters a family with a tent and bedding.",
      "One hundred percent of donations to this campaign go directly to relief goods — SMIT covers all administrative and logistics costs separately, as it does across all Saylani relief operations.",
    ],
    imageUrl: "/media/flood-shelter.jpg",
    gallery: [
      "/media/flood-shelter.jpg",
      img("photo-1488521787991-ed7bbaae773c"),
      img("photo-1593113598332-cd288d649433"),
    ],
    category: "Emergency",
    location: "Sindh",
    goalAmount: 5000000,
    raisedAmount: 3265000,
    donorCount: 890,
    currency: "PKR",
    status: "urgent",
    createdAt: "2026-06-18T06:00:00Z",
    endsAt: "2026-08-15T23:59:59Z",
  },
  {
    id: "c3",
    slug: "clean-water-wells-thar",
    title: "Clean Water Wells in Tharparkar",
    tagline: "Dig deep-water wells for villages walking miles for every drop.",
    description:
      "Families in Thar walk up to 8 km daily for brackish water. Each solar-powered deep well serves an entire village with clean, safe drinking water for decades.",
    story: [
      "In the Thar desert, water is life's daily struggle. Women and children spend hours each day walking to distant, often contaminated sources — hours that should be spent in school or earning a livelihood.",
      "One deep-water well costs Rs. 450,000 fully installed, including a solar pump and storage tank, and serves 300–500 people for 20+ years. That works out to less than Rs. 1,500 per person for a generation of clean water.",
      "Wells are geo-tagged and photographed on completion, and donors who fund a full well receive the coordinates and photos of their well in operation.",
    ],
    imageUrl: img("photo-1501854140801-50d01698950b"),
    gallery: [
      img("photo-1501854140801-50d01698950b"),
      img("photo-1470071459604-3b5ec3a7fe05"),
      img("photo-1488521787991-ed7bbaae773c"),
    ],
    category: "Clean Water",
    location: "Tharparkar",
    goalAmount: 1800000,
    raisedAmount: 962000,
    donorCount: 233,
    currency: "PKR",
    status: "active",
    createdAt: "2026-02-01T09:00:00Z",
    endsAt: "2026-10-31T23:59:59Z",
  },
  {
    id: "c4",
    slug: "daily-dastarkhwan-meals",
    title: "Daily Dastarkhwan: 10,000 Meals a Day",
    tagline: "Keep the daily free meal service running for laborers and families.",
    description:
      "Our dastarkhwan serves fresh, hot meals every single day to daily-wage workers, students, and families in need. Rs. 200 feeds one person a full meal.",
    story: [
      "Every day at noon, queues form outside our dastarkhwan locations — daily-wage laborers between jobs, students far from home, elderly citizens with no support. No one is asked questions. Everyone is fed.",
      "Running this service costs roughly Rs. 2 million a month across our locations. Rs. 200 covers one full meal; Rs. 6,000 feeds one person for a month; Rs. 60,000 sponsors an entire day's service at one location.",
      "This campaign keeps the stoves lit through the next quarter. Whatever you give becomes a hot plate of food in someone's hands — usually within 24 hours.",
    ],
    imageUrl: img("photo-1504674900247-0877df9cc836"),
    gallery: [
      img("photo-1504674900247-0877df9cc836"),
      img("photo-1593113598332-cd288d649433"),
      img("photo-1532629345422-7515f3d16bb6"),
    ],
    category: "Food Relief",
    location: "Karachi",
    goalAmount: 3000000,
    raisedAmount: 2715000,
    donorCount: 1204,
    currency: "PKR",
    status: "active",
    createdAt: "2026-04-01T09:00:00Z",
    endsAt: "2026-09-30T23:59:59Z",
  },
  {
    id: "c5",
    slug: "free-medical-camp-diagnostics",
    title: "Free Medical Camps & Diagnostics",
    tagline: "Bring doctors, medicines, and lab tests to underserved neighborhoods.",
    description:
      "Monthly medical camps offering free consultations, essential medicines, and diagnostic tests for communities with no access to affordable healthcare.",
    story: [
      "For millions of Pakistanis, a simple doctor's visit means choosing between medicine and dinner. Our free medical camps bring qualified doctors, essential medicines, and basic diagnostics directly into underserved neighborhoods.",
      "Each camp serves 400–600 patients in a day. Rs. 1,000 covers one patient's consultation and medicines; Rs. 25,000 funds the medicine stock for a full camp; Rs. 150,000 sponsors an entire camp including lab diagnostics.",
      "Early detection at these camps has caught hundreds of cases of diabetes and hypertension before they became emergencies — care that costs rupees today instead of lakhs tomorrow.",
    ],
    imageUrl: "/media/community-2.jpg",
    gallery: [
      "/media/community-2.jpg",
      img("photo-1576091160399-112ba8d25d1d"),
      img("photo-1469571486292-0ba58a3f068b"),
    ],
    category: "Healthcare",
    location: "Lahore",
    goalAmount: 2200000,
    raisedAmount: 640000,
    donorCount: 158,
    currency: "PKR",
    status: "active",
    createdAt: "2026-05-10T09:00:00Z",
    endsAt: "2026-11-30T23:59:59Z",
  },
  {
    id: "c6",
    slug: "orphan-education-care",
    title: "Orphan Education & Care Program",
    tagline: "School fees, uniforms, and mentorship for orphaned children.",
    description:
      "Full educational support for orphaned children — school fees, books, uniforms, meals, and a dedicated mentor who follows each child's progress.",
    story: [
      "Losing a parent should never mean losing a future. This program enrolls orphaned children in quality schools and surrounds them with the support system a parent would provide.",
      "Rs. 8,000 a month covers one child completely: fees, books, uniform, daily meal, and transport. Our mentorship team visits each family monthly and tracks every child's attendance and grades.",
      "This campaign reached its goal thanks to 300+ generous donors — enrollment for the new academic year is fully funded. New donations roll into next year's cohort.",
    ],
    imageUrl: img("photo-1509099836639-18ba1795216d"),
    gallery: [
      img("photo-1509099836639-18ba1795216d"),
      img("photo-1524995997946-a1c2e315a42f"),
      img("photo-1503676260728-1c00da094a0b"),
    ],
    category: "Orphan Care",
    location: "Karachi",
    goalAmount: 1500000,
    raisedAmount: 1500000,
    donorCount: 327,
    currency: "PKR",
    status: "completed",
    createdAt: "2026-01-05T09:00:00Z",
    endsAt: "2026-06-30T23:59:59Z",
  },
  {
    id: "c7",
    slug: "womens-it-bootcamp-scholarships",
    title: "Women's IT Bootcamp Scholarships",
    tagline: "Open the door to tech careers for 100 women this year.",
    description:
      "Dedicated scholarships for women entering SMIT's web and mobile development bootcamps, including transport stipends that make attendance possible.",
    story: [
      "Talent is equally distributed; opportunity is not. Many capable women in our communities can't join tech training because of transport costs, family obligations, or simple lack of funds.",
      "This fund removes those barriers: Rs. 20,000 sponsors one woman's full bootcamp seat, and Rs. 5,000 more covers a transport stipend for the duration — often the single factor that decides whether she can attend.",
      "Graduates from previous cohorts now work as developers, freelancers, and instructors. Several have become the primary earners in their households.",
    ],
    imageUrl: img("photo-1503676260728-1c00da094a0b"),
    gallery: [
      img("photo-1503676260728-1c00da094a0b"),
      img("photo-1461749280684-dccba630e2f6"),
      img("photo-1524995997946-a1c2e315a42f"),
    ],
    category: "Education",
    location: "Karachi",
    goalAmount: 2000000,
    raisedAmount: 1235000,
    donorCount: 289,
    currency: "PKR",
    status: "active",
    createdAt: "2026-03-01T09:00:00Z",
    endsAt: "2026-12-31T23:59:59Z",
  },
  {
    id: "c8",
    slug: "monthly-ration-drive",
    title: "Monthly Ration Drive for Widows & Elderly",
    tagline: "A month of groceries delivered to doorsteps that have no one else.",
    description:
      "Monthly ration packs — flour, rice, lentils, oil, tea, and essentials — delivered to widows, the elderly, and families with disabled breadwinners.",
    story: [
      "Behind many doors in our cities live people the economy has forgotten: widows raising children alone, elderly couples with no support, families whose breadwinner is disabled. Pride keeps many from ever asking for help.",
      "Our verified beneficiary list is built through home visits by volunteers. Rs. 7,500 delivers a complete month's ration pack to one family's doorstep, discreetly and with dignity.",
      "We are currently short of funds for this month's 500-family distribution — this drive is time-sensitive, as packs must be delivered in the first week of the month.",
    ],
    imageUrl: "/media/community-1.jpg",
    gallery: [
      "/media/community-1.jpg",
      "/media/hands-giving.avif",
      img("photo-1532629345422-7515f3d16bb6"),
    ],
    category: "Food Relief",
    location: "Hyderabad",
    goalAmount: 1200000,
    raisedAmount: 410000,
    donorCount: 97,
    currency: "PKR",
    status: "urgent",
    createdAt: "2026-06-25T09:00:00Z",
    endsAt: "2026-07-20T23:59:59Z",
  },
  {
    id: "c9",
    slug: "dialysis-support-fund",
    title: "Dialysis Support Fund",
    tagline: "Life-sustaining dialysis sessions for patients who cannot pay.",
    description:
      "Kidney patients need dialysis 2–3 times weekly to survive. This fund covers sessions, transport, and medicines for patients with no means to pay.",
    story: [
      "Dialysis is not a treatment you can skip — for kidney failure patients it is life itself, needed two to three times every week, indefinitely. At market rates that is over Rs. 40,000 a month, far beyond a laborer's income.",
      "Rs. 3,500 funds one complete dialysis session including consumables. Rs. 42,000 keeps one patient alive for a month. Our partner units verify every patient's financial status.",
      "This fund is nearly at goal — the last stretch ensures no enrolled patient misses a session next quarter.",
    ],
    imageUrl: "/media/community-3.jpg",
    gallery: [
      "/media/community-3.jpg",
      "/media/community-2.jpg",
      img("photo-1576091160399-112ba8d25d1d"),
    ],
    category: "Healthcare",
    location: "Karachi",
    goalAmount: 4000000,
    raisedAmount: 3980000,
    donorCount: 1456,
    currency: "PKR",
    status: "active",
    createdAt: "2026-01-15T09:00:00Z",
    endsAt: "2026-08-31T23:59:59Z",
  },
  {
    id: "c10",
    slug: "village-school-rebuild",
    title: "Village School Rebuild — Badin",
    tagline: "Rebuilt classrooms, new furniture, and supplies for 240 children.",
    description:
      "The only primary school serving three villages was damaged beyond use. We rebuilt its four classrooms, furnished them, and stocked a year of supplies.",
    story: [
      "When the school in this Badin village became structurally unsafe, 240 children simply stopped going to school — the next nearest one was 12 km away.",
      "Donors funded the complete rebuild: four classrooms, proper ventilation, desks and chairs, a small library corner, and a year's stock of learning materials.",
      "Classes resumed this spring with attendance higher than before the closure. This campaign is complete — thank you to the 180 donors who made it happen.",
    ],
    imageUrl: img("photo-1524995997946-a1c2e315a42f"),
    gallery: [
      img("photo-1524995997946-a1c2e315a42f"),
      img("photo-1503676260728-1c00da094a0b"),
      img("photo-1509099836639-18ba1795216d"),
    ],
    category: "Education",
    location: "Badin",
    goalAmount: 900000,
    raisedAmount: 900000,
    donorCount: 180,
    currency: "PKR",
    status: "completed",
    createdAt: "2025-11-10T09:00:00Z",
    endsAt: "2026-03-31T23:59:59Z",
  },
];
