/**
 * Builds a Word (.docx) report from tabular data — used by the AI agent's
 * generate_word_report tool so admins/trainers can ask for "a document" of
 * any analysis and get a real downloadable file back.
 */
import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from "docx";
import { GridFSBucket } from "mongodb";
import { mongo } from "@/lib/mongodb";

const slugify = (text: string) =>
  text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60) || "report";

/** Stores a generated .docx in MongoDB GridFS and returns a download link
 *  served by /api/reports/[id] (session-gated). */
export async function uploadWordReport(
  buffer: Buffer,
  title: string,
): Promise<{ url: string; filename: string }> {
  const filename = `${slugify(title)}-${Date.now()}.docx`;
  const db = await mongo();
  const bucket = new GridFSBucket(db, { bucketName: "reports" });

  const id = await new Promise<string>((resolve, reject) => {
    const stream = bucket.openUploadStream(filename, {
      metadata: { contentType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
    });
    stream.on("error", reject);
    stream.on("finish", () => resolve(String(stream.id)));
    stream.end(buffer);
  });

  return { url: `/api/reports/${id}`, filename };
}

const BRAND_BLUE = "0B73B7";
const BRAND_GREEN = "6DA800";

function headerCell(text: string): TableCell {
  return new TableCell({
    shading: { fill: BRAND_BLUE },
    children: [
      new Paragraph({
        children: [new TextRun({ text, bold: true, color: "FFFFFF", size: 20 })],
      }),
    ],
  });
}

function dataCell(text: string, shaded: boolean): TableCell {
  return new TableCell({
    shading: shaded ? { fill: "F3F7FA" } : undefined,
    children: [new Paragraph({ children: [new TextRun({ text, size: 20 })] })],
  });
}

export interface WordReportInput {
  title: string;
  intro?: string;
  columns: string[];
  rows: string[][];
  generatedFor: string;
}

export async function buildWordReport({
  title,
  intro,
  columns,
  rows,
  generatedFor,
}: WordReportInput): Promise<Buffer> {
  const headerRow = new TableRow({ children: columns.map(headerCell), tableHeader: true });
  const bodyRows = rows.map(
    (row, i) =>
      new TableRow({
        children: row.map((cell) => dataCell(String(cell ?? ""), i % 2 === 1)),
      }),
  );

  const table = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [headerRow, ...bodyRows],
  });

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            children: [new TextRun({ text: "SMIT — Saylani Mass IT Training", bold: true, color: BRAND_GREEN, size: 20 })],
          }),
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            spacing: { after: 160 },
            children: [new TextRun({ text: title, color: BRAND_BLUE })],
          }),
          ...(intro
            ? [new Paragraph({ spacing: { after: 200 }, children: [new TextRun({ text: intro, size: 22 })] })]
            : []),
          new Paragraph({
            spacing: { after: 240 },
            children: [
              new TextRun({
                text: `Generated for ${generatedFor} on ${new Date().toISOString().slice(0, 10)} · ${rows.length} record${rows.length === 1 ? "" : "s"}`,
                italics: true,
                size: 18,
                color: "6F6F6F",
              }),
            ],
          }),
          table,
          new Paragraph({
            spacing: { before: 300 },
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: "Generated by Saylani Intelligence — SMIT Donations AI Assistant",
                size: 16,
                color: "9CA3AF",
              }),
            ],
          }),
        ],
      },
    ],
  });

  return Packer.toBuffer(doc);
}
